// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:flutter_bloc_starter_kit/features/taxonomy/data/models/taxonomy_fact_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(TaxonomyFactAdapter());
    registerAdapter(TaxonomyTypeAdapter());
  }
}
